name: sharedflow-ci
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Deploy To Dev"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: Install Apigee CLI
        run: |
          curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -
          echo "$HOME/.apigeecli/bin" >> $GITHUB_PATH
      - name: Create API bundle
        run: zip -r sharedflow.zip sharedflowbundle
        working-directory: sharedflowbundles/examplesharedflow
      - name: Upload API proxy bundle
        run: |
          apigeecli sharedflows import --org se-apigee-playground \
            -f sharedflowbundles/examplesharedflow \
            --default-token
      - name: Deploy Revision
        run: |
          apigeecli sharedflows deploy --org se-apigee-playground \
            --name samplesharedflow \
            --env dev \
            --ovr \
            --sa proxy-deployment@se-apigee-playground.iam.gserviceaccount.com \
            --default-token